---
- name: Create a change request in ServiceNow
  servicenow.itsm.change_request:
    state: new
    type: standard
    template: "Reboot Windows Server - 1"
    short_description: "Reboot Windows Server"
    requested_by: admin
    other:
      cmdb_ci: "{{ ip_addr }}"
  delegate_to: localhost
  register: request

- name: Pass along request information
  ansible.builtin.set_stats:
    data:
      request: "{{ request }}"
    per_host: no
