---
- name: Update SNOW CMDB
  servicenow.itsm.configuration_item:
    state: "{{ status }}"
    asset_tag: "{{ owner }}"
    name: "{{ inventory_hostname }}"
    ip_address: "{{ ip_addr | default(omit) }}"
    sys_class_name: cmdb_ci_server
    sys_id: "{{ sys_id | default(omit) }}"
    other:
      classification: "{{ env | default(omit) }}"
      fqdn: "{{ fqdn | default(omit) }}"
      os: "{{ os | default(omit) }}"
      host_name: "{{ inventory_hostname }}"
  delegate_to: localhost
